## Changes:
Zocom-LIA/codecrafters-quizapp pull request #29
Opened 2024-10-17 21:49 UTC by camelliahayati

- Updated `script.js` to handle API calls, localStorage, and dynamic quiz content.
- Updated `description.html` to render quiz details and navigate to the question page.

2024-10-23 07:02 UTC, ioannismarkou requested changes
Great work! 

The quiz description is shown as expected. Very good thought of storing data in storage instead of the url parameters! :)

Just make sure to re-add the line I specified so that the quizzes can load.

2024-10-23 12:12 UTC, Sheela-cla commented
Great work! Camelia
  I tested locally as Yannis said I couldn't see quizzes in Home page.

2024-10-23 12:26 UTC, Sheela-cla requested changes
frontend/script.js
Quizzes is not loaded at home page when I tested locally

2024-10-24 07:11 UTC, ioannismarkou commented
> frontend/script.js Quizzes is not loaded at home page when I tested locally

Fixed.

2024-10-24 09:30 UTC, NegarMadadi approved these changes
Great job Camellia, Thank you.

2024-10-24 09:31 UTC, farah-najib approved these changes

2024-10-31 10:17 UTC, closed without merging

2024-10-31 10:17 UTC, ioannismarkou commented
Closing as all changes of this PR are merged into the issue #30 .